### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [mrityunjay-tripathi/traffic-management#1]
I am getting Memory Error, as I can guess there is somewhere memory leak but I can't locate it.
This is the error I am getting.

Traceback (most recent call last):
  File "detection.py", line 124, in <module>
    net = d.train(train_loader)
  File "detection.py", line 55, in train
    for data in trainloader:
  File "/home/mrityunjay/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/mrityunjay/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/mrityunjay/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/mrityunjay/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/mrityunjay/anaconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/mrityunjay/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/mrityunjay/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by mrityunjay-tripathi** [comment]
Ok, got it!
I tried reducing the out_features in nn.Linear and it worked for me.
